version: '3'

services:
  db_mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ihurry
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_PASSWORD: supersecret
      MYSQL_USER: mysql
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - '6379:6379'

  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

  # db_mongo:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   ports:
  #     - "27017:27017"
