version: '3'

services:
  db_mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ihurry
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_PASSWORD: supersecret
      MYSQL_USER: mysql

  # db_mongo:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   ports:
  #     - "27017:27017"
